// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "ui.h"

void gpio_test_initcb(lv_event_t *e)
{
    led_test();
}

void isr_test_initcb(lv_event_t *e)
{
    isr_test();
}

void uart_test_initcb(lv_event_t *e)
{
    uart_test_init();
}

void i2c_test_initcb(lv_event_t *e)
{
    // Your code here
}

void spi_test_initcb(lv_event_t *e)
{
    spi_mutex_init();
}

void backlight(lv_event_t *e)
{
    // Your code here
}

void volumesetting(lv_event_t *e)
{
    // Your code here
}

void isrTestCb_1(lv_event_t *e)
{
    isr1_event_cb(e);
}

void isrTestCb_2(lv_event_t *e)
{
    isr2_event_cb(e);
}

void timeTestCb(lv_event_t *e)
{
    // Your code here
}

void adTestCb(lv_event_t *e)
{
    // Your code here
}

void pwmTestCb(lv_event_t *e)
{
    // Your code here
}

void clean_uartuicb(lv_event_t *e)
{
    // Your code here
}

void uartKeyBoardTxCb(lv_event_t *e)
{
    const char *data = lv_textarea_get_text(ui_txtext);
    char str[50];
    sprintf(str, "%s", data);
    uart_tx_test(str);
}

void clean_i2cuicb(lv_event_t *e)
{
    // Your code here
}

void i2cKeyBoardTxCb(lv_event_t *e)
{
    // Your code here
}

void clean_spiuicb(lv_event_t *e)
{
    clean_spiui();
}

void spiKeyBoardTxCb(lv_event_t *e)
{
    const char *data = lv_textarea_get_text(ui_spitxtext);
    char str[SPI_TEST_BUF];
    sprintf(str, "%s", data);

    spi_test(str);
}

void spi_maste_initcb(lv_event_t *e)
{
    spi_master_init();
}

void spi_slave_initcb(lv_event_t *e)
{
    spi_slave_init();
}

void wifiscanf(lv_event_t *e)
{
    // Your code here
}

void wifistart(lv_event_t *e)
{
    // Your code here
}

void wificlose(lv_event_t *e)
{
    // Your code here
}

void wifisanf(lv_event_t *e)
{
    // Your code here
}

void connectwifi(lv_event_t *e)
{
    // Your code here
}
