// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_adui_screen_init(void)
{
    ui_adui = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_adui, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_adheader = lv_obj_create(ui_adui);
    lv_obj_set_width(ui_adheader, lv_pct(100));
    lv_obj_set_height(ui_adheader, lv_pct(20));
    lv_obj_set_align(ui_adheader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_adheader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_adheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_adheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_adheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_adheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_adheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_adheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_adheader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_adheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_adheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_adheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_adheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_adheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_adheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_adheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_adheader, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adtitle = lv_label_create(ui_adheader);
    lv_obj_set_width(ui_adtitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_adtitle, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_adtitle, 30);
    lv_obj_set_y(ui_adtitle, -2);
    lv_obj_set_align(ui_adtitle, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_adtitle, "AD实验");

    ui_adpanel = lv_obj_create(ui_adui);
    lv_obj_set_width(ui_adpanel, lv_pct(100));
    lv_obj_set_height(ui_adpanel, lv_pct(80));
    lv_obj_set_x(ui_adpanel, lv_pct(0));
    lv_obj_set_y(ui_adpanel, lv_pct(20));
    lv_obj_set_align(ui_adpanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_adpanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_adpanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_adpanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_adpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_adpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_adpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_adpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_adchart = lv_chart_create(ui_adpanel);
    lv_obj_set_width(ui_adchart, lv_pct(100));
    lv_obj_set_height(ui_adchart, lv_pct(100));
    lv_obj_set_x(ui_adchart, 37);
    lv_obj_set_y(ui_adchart, -6);
    lv_obj_set_align(ui_adchart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_adchart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_adchart, 300);
    lv_chart_set_range(ui_adchart, LV_CHART_AXIS_PRIMARY_Y, 0, 4095);
    lv_chart_set_range(ui_adchart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_adchart, 20, 40);
    lv_chart_set_axis_tick(ui_adchart, LV_CHART_AXIS_PRIMARY_X, 7, 5, 20, 2, false, 50);
    lv_chart_set_axis_tick(ui_adchart, LV_CHART_AXIS_PRIMARY_Y, 5, 2, 10, 2, true, 20);
    lv_chart_set_axis_tick(ui_adchart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);

    lv_obj_add_event_cb(ui_adui, ui_event_adui, LV_EVENT_ALL, NULL);
}
