// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_daui_screen_init(void)
{
    ui_daui = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_daui, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_daheader = lv_obj_create(ui_daui);
    lv_obj_set_width(ui_daheader, lv_pct(100));
    lv_obj_set_height(ui_daheader, lv_pct(20));
    lv_obj_set_align(ui_daheader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_daheader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_daheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_daheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_daheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_daheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_daheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_daheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_daheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_daheader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_daheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_daheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_daheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_daheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_daheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_daheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_daheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_daheader, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_datitle = lv_label_create(ui_daheader);
    lv_obj_set_width(ui_datitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_datitle, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_datitle, 30);
    lv_obj_set_y(ui_datitle, -2);
    lv_obj_set_align(ui_datitle, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_datitle, "DA实验");

    ui_dapanel = lv_obj_create(ui_daui);
    lv_obj_set_width(ui_dapanel, lv_pct(100));
    lv_obj_set_height(ui_dapanel, lv_pct(80));
    lv_obj_set_x(ui_dapanel, lv_pct(0));
    lv_obj_set_y(ui_dapanel, lv_pct(20));
    lv_obj_set_align(ui_dapanel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_dapanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_scrollbar_mode(ui_dapanel, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_radius(ui_dapanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dapanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dapanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dapanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_daui, ui_event_daui, LV_EVENT_ALL, NULL);
}
