// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_gpioui_screen_init(void)
{
ui_gpioui = lv_obj_create(NULL);
lv_obj_clear_flag( ui_gpioui, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_gpioheader = lv_obj_create(ui_gpioui);
lv_obj_set_width( ui_gpioheader, lv_pct(100));
lv_obj_set_height( ui_gpioheader, lv_pct(20));
lv_obj_set_align( ui_gpioheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_gpioheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_gpioheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_gpioheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpioheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpioheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_gpioheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_gpioheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpioheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_gpioheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_gpioheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gpioheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpioheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpiotitle = lv_label_create(ui_gpioheader);
lv_obj_set_width( ui_gpiotitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpiotitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpiotitle, 30 );
lv_obj_set_y( ui_gpiotitle, -2 );
lv_obj_set_align( ui_gpiotitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_gpiotitle,"GPIO实验");

ui_gpiopanel = lv_obj_create(ui_gpioui);
lv_obj_set_width( ui_gpiopanel, lv_pct(100));
lv_obj_set_height( ui_gpiopanel, lv_pct(80));
lv_obj_set_x( ui_gpiopanel, lv_pct(0) );
lv_obj_set_y( ui_gpiopanel, lv_pct(20) );
lv_obj_set_align( ui_gpiopanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_gpiopanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpiopanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpiopanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpiopanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpiopanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_gpioui, ui_event_gpioui, LV_EVENT_ALL, NULL);

}
