// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_home_screen_init(void)
{
ui_home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_home,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_home, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_home, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_home, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_header = lv_obj_create(ui_home);
lv_obj_set_width( ui_header, lv_pct(100));
lv_obj_set_height( ui_header, lv_pct(20));
lv_obj_set_align( ui_header, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_header,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_header, LV_OBJ_FLAG_FLOATING );   /// Flags
lv_obj_clear_flag( ui_header, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_header, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_header, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mobile = lv_label_create(ui_header);
lv_obj_set_width( ui_mobile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mobile, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mobile, 10 );
lv_obj_set_y( ui_mobile, 7 );
lv_label_set_text(ui_mobile,"中国移动");
lv_obj_clear_flag( ui_mobile, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_mobile, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mobile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_label_create(ui_header);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, 0 );
lv_obj_set_y( ui_time, 7 );
lv_obj_set_align( ui_time, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_time,"12:12");
lv_obj_clear_flag( ui_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi = lv_label_create(ui_header);
lv_obj_set_width( ui_wifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi, 78 );
lv_obj_set_y( ui_wifi, 7 );
lv_label_set_text(ui_wifi,"");
lv_obj_clear_flag( ui_wifi, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifi, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_body = lv_obj_create(ui_home);
lv_obj_set_width( ui_body, lv_pct(100));
lv_obj_set_height( ui_body, lv_pct(80));
lv_obj_set_x( ui_body, lv_pct(0) );
lv_obj_set_y( ui_body, lv_pct(10) );
lv_obj_set_align( ui_body, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_body,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_body, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_body, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_body, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_body, LV_DIR_HOR);
lv_obj_set_style_radius(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_body, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_body, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_home1 = lv_obj_create(ui_body);
lv_obj_set_width( ui_home1, lv_pct(100));
lv_obj_set_height( ui_home1, lv_pct(100));
lv_obj_set_align( ui_home1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_home1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_home1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_home1, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_home1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_home1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_home1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_home1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_home1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_home1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpiobtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_gpiobtn, lv_pct(30));
lv_obj_set_height( ui_gpiobtn, lv_pct(30));
lv_obj_set_x( ui_gpiobtn, 108 );
lv_obj_set_y( ui_gpiobtn, 21 );
lv_obj_set_align( ui_gpiobtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_gpiobtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_gpiobtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_gpiobtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_gpiobtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_gpiolabel = lv_label_create(ui_gpiobtn);
lv_obj_set_width( ui_gpiolabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpiolabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpiolabel, 154 );
lv_obj_set_y( ui_gpiolabel, 55 );
lv_obj_set_align( ui_gpiolabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_gpiolabel,"GPIO");

ui_isrbtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_isrbtn, lv_pct(30));
lv_obj_set_height( ui_isrbtn, lv_pct(30));
lv_obj_set_x( ui_isrbtn, 108 );
lv_obj_set_y( ui_isrbtn, 21 );
lv_obj_set_align( ui_isrbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_isrbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_isrbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_isrbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_isrbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_isrlabel = lv_label_create(ui_isrbtn);
lv_obj_set_width( ui_isrlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_isrlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_isrlabel, 154 );
lv_obj_set_y( ui_isrlabel, 55 );
lv_obj_set_align( ui_isrlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_isrlabel,"ISR");

ui_timebtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_timebtn, lv_pct(30));
lv_obj_set_height( ui_timebtn, lv_pct(30));
lv_obj_set_x( ui_timebtn, 108 );
lv_obj_set_y( ui_timebtn, 21 );
lv_obj_set_align( ui_timebtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timebtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_timebtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_timebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_timebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timelabel = lv_label_create(ui_timebtn);
lv_obj_set_width( ui_timelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timelabel, 154 );
lv_obj_set_y( ui_timelabel, 55 );
lv_obj_set_align( ui_timelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timelabel,"TIMER");

ui_adbtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_adbtn, lv_pct(30));
lv_obj_set_height( ui_adbtn, lv_pct(30));
lv_obj_set_x( ui_adbtn, -170 );
lv_obj_set_y( ui_adbtn, -20 );
lv_obj_set_align( ui_adbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_adbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_adbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_adbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_adbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_adlabel = lv_label_create(ui_adbtn);
lv_obj_set_width( ui_adlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adlabel, 154 );
lv_obj_set_y( ui_adlabel, 55 );
lv_obj_set_align( ui_adlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_adlabel,"ADC");

ui_pwmbtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_pwmbtn, lv_pct(30));
lv_obj_set_height( ui_pwmbtn, lv_pct(30));
lv_obj_set_x( ui_pwmbtn, 618 );
lv_obj_set_y( ui_pwmbtn, 4 );
lv_obj_set_align( ui_pwmbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_pwmbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_pwmbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_pwmbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_pwmbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pwmlabel = lv_label_create(ui_pwmbtn);
lv_obj_set_width( ui_pwmlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pwmlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pwmlabel, 154 );
lv_obj_set_y( ui_pwmlabel, 55 );
lv_obj_set_align( ui_pwmlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pwmlabel,"PWM");

ui_dabtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_dabtn, lv_pct(30));
lv_obj_set_height( ui_dabtn, lv_pct(30));
lv_obj_set_x( ui_dabtn, 108 );
lv_obj_set_y( ui_dabtn, 21 );
lv_obj_set_align( ui_dabtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_dabtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_dabtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_dabtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_dabtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dalabel = lv_label_create(ui_dabtn);
lv_obj_set_width( ui_dalabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dalabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dalabel, 154 );
lv_obj_set_y( ui_dalabel, 55 );
lv_obj_set_align( ui_dalabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_dalabel,"DAC");

ui_home2 = lv_obj_create(ui_body);
lv_obj_set_width( ui_home2, lv_pct(100));
lv_obj_set_height( ui_home2, lv_pct(100));
lv_obj_set_x( ui_home2, 280 );
lv_obj_set_y( ui_home2, 2 );
lv_obj_set_align( ui_home2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_home2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_home2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_home2, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_home2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_home2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_home2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_home2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_home2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_home2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uartbtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_uartbtn, lv_pct(30));
lv_obj_set_height( ui_uartbtn, lv_pct(30));
lv_obj_set_x( ui_uartbtn, 108 );
lv_obj_set_y( ui_uartbtn, 21 );
lv_obj_set_align( ui_uartbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uartbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_uartbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_uartbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_uartbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uartlabel = lv_label_create(ui_uartbtn);
lv_obj_set_width( ui_uartlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uartlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uartlabel, 154 );
lv_obj_set_y( ui_uartlabel, 55 );
lv_obj_set_align( ui_uartlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_uartlabel,"UART");

ui_i2cbtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_i2cbtn, lv_pct(30));
lv_obj_set_height( ui_i2cbtn, lv_pct(30));
lv_obj_set_x( ui_i2cbtn, 108 );
lv_obj_set_y( ui_i2cbtn, 21 );
lv_obj_set_align( ui_i2cbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_i2cbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_i2cbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_i2cbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_i2cbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_i2clabel = lv_label_create(ui_i2cbtn);
lv_obj_set_width( ui_i2clabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_i2clabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_i2clabel, 154 );
lv_obj_set_y( ui_i2clabel, 55 );
lv_obj_set_align( ui_i2clabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_i2clabel,"I2C");

ui_spibtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_spibtn, lv_pct(30));
lv_obj_set_height( ui_spibtn, lv_pct(30));
lv_obj_set_x( ui_spibtn, 108 );
lv_obj_set_y( ui_spibtn, 21 );
lv_obj_set_align( ui_spibtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_spibtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_spibtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_spibtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_spibtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spilabel = lv_label_create(ui_spibtn);
lv_obj_set_width( ui_spilabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spilabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spilabel, 154 );
lv_obj_set_y( ui_spilabel, 55 );
lv_obj_set_align( ui_spilabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_spilabel,"SPI");

ui_mqttbtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_mqttbtn, lv_pct(30));
lv_obj_set_height( ui_mqttbtn, lv_pct(30));
lv_obj_set_x( ui_mqttbtn, 108 );
lv_obj_set_y( ui_mqttbtn, 21 );
lv_obj_set_align( ui_mqttbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mqttbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_mqttbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_mqttbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_mqttbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mqttlabel = lv_label_create(ui_mqttbtn);
lv_obj_set_width( ui_mqttlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqttlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mqttlabel, 154 );
lv_obj_set_y( ui_mqttlabel, 55 );
lv_obj_set_align( ui_mqttlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_mqttlabel,"MQTT");

ui_menudown = lv_obj_create(ui_home);
lv_obj_set_width( ui_menudown, lv_pct(100));
lv_obj_set_height( ui_menudown, lv_pct(100));
lv_obj_set_x( ui_menudown, 0 );
lv_obj_set_y( ui_menudown, -240 );
lv_obj_set_align( ui_menudown, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_menudown,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_menudown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_menudown, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_menudown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_menudown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_menudown, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_menudown, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menudown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_menudowntop = lv_obj_create(ui_menudown);
lv_obj_set_width( ui_menudowntop, lv_pct(100));
lv_obj_set_height( ui_menudowntop, lv_pct(30));
lv_obj_set_align( ui_menudowntop, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_menudowntop,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_menudowntop, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_menudowntop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_menudowntop, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menudowntop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifibtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_wifibtn, 50);
lv_obj_set_height( ui_wifibtn, 50);
lv_obj_set_align( ui_wifibtn, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_wifibtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifibtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wifibtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifibtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifibtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifibtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_wifibtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_wifibtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_wifibtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_wifilabel = lv_label_create(ui_wifibtn);
lv_obj_set_width( ui_wifilabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifilabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifilabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifilabel,"");

ui_bluebtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_bluebtn, 50);
lv_obj_set_height( ui_bluebtn, 50);
lv_obj_set_x( ui_bluebtn, 68 );
lv_obj_set_y( ui_bluebtn, 0 );
lv_obj_set_align( ui_bluebtn, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_bluebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_bluebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_bluebtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bluebtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bluebtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bluebtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_bluebtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_bluebtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_bluebtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_bluelabel = lv_label_create(ui_bluebtn);
lv_obj_set_width( ui_bluelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bluelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bluelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_bluelabel,"");

ui_gpsbtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_gpsbtn, 50);
lv_obj_set_height( ui_gpsbtn, 50);
lv_obj_set_x( ui_gpsbtn, -68 );
lv_obj_set_y( ui_gpsbtn, 0 );
lv_obj_set_align( ui_gpsbtn, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_gpsbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_gpsbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpsbtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpsbtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpsbtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpsbtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_gpsbtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_gpsbtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_gpsbtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_mutelabel1 = lv_label_create(ui_gpsbtn);
lv_obj_set_width( ui_mutelabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mutelabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mutelabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_mutelabel1,"");

ui_settinglbtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_settinglbtn, 50);
lv_obj_set_height( ui_settinglbtn, 50);
lv_obj_set_align( ui_settinglbtn, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_settinglbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_settinglbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_settinglbtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_settinglbtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settinglbtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_settinglbtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_settinglbtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_settinglbtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_settinglbtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_settinglabel = lv_label_create(ui_settinglbtn);
lv_obj_set_width( ui_settinglabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settinglabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_settinglabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_settinglabel,"");

ui_lightslider = lv_slider_create(ui_menudown);
lv_slider_set_value( ui_lightslider, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_lightslider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_lightslider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_lightslider, lv_pct(100));
lv_obj_set_height( ui_lightslider, lv_pct(16));
lv_obj_set_align( ui_lightslider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_lightslider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lightslider, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightslider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_lightslider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_lightslider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lightslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightslider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_lightslider, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lightslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightslider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lighttext = lv_label_create(ui_lightslider);
lv_obj_set_width( ui_lighttext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lighttext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lighttext, 10 );
lv_obj_set_y( ui_lighttext, 0 );
lv_obj_set_align( ui_lighttext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_lighttext,"");
lv_obj_set_style_text_color(ui_lighttext, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lighttext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lighttext, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_volumeslider = lv_slider_create(ui_menudown);
lv_slider_set_value( ui_volumeslider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_volumeslider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_volumeslider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_volumeslider, lv_pct(100));
lv_obj_set_height( ui_volumeslider, lv_pct(16));
lv_obj_set_align( ui_volumeslider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_volumeslider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_volumeslider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_volumeslider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_volumeslider, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeslider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_volumetext = lv_label_create(ui_volumeslider);
lv_obj_set_width( ui_volumetext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_volumetext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_volumetext, 10 );
lv_obj_set_y( ui_volumetext, 0 );
lv_obj_set_align( ui_volumetext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_volumetext,"");
lv_obj_set_style_text_color(ui_volumetext, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_volumetext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_volumetext, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_menudownfoot = lv_obj_create(ui_menudown);
lv_obj_set_width( ui_menudownfoot, lv_pct(17));
lv_obj_set_height( ui_menudownfoot, lv_pct(1));
lv_obj_set_x( ui_menudownfoot, 0 );
lv_obj_set_y( ui_menudownfoot, lv_pct(100) );
lv_obj_set_align( ui_menudownfoot, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_menudownfoot, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_menudownfoot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_menudownfoot, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_menudownfoot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menudownfoot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_header, ui_event_header, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_gpiobtn, ui_event_gpiobtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_isrbtn, ui_event_isrbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_timebtn, ui_event_timebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adbtn, ui_event_adbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pwmbtn, ui_event_pwmbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dabtn, ui_event_dabtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uartbtn, ui_event_uartbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_i2cbtn, ui_event_i2cbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spibtn, ui_event_spibtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifibtn, ui_event_wifibtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bluebtn, ui_event_bluebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_gpsbtn, ui_event_gpsbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settinglbtn, ui_event_settinglbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_lightslider, ui_event_lightslider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_volumeslider, ui_event_volumeslider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_menudown, ui_event_menudown, LV_EVENT_ALL, NULL);

}
