// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_home_screen_init(void)
{
ui_home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_home,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_home, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_home, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_home, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_header = lv_obj_create(ui_home);
lv_obj_set_width( ui_header, lv_pct(100));
lv_obj_set_height( ui_header, lv_pct(20));
lv_obj_set_align( ui_header, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_header,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_header, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_header, LV_OBJ_FLAG_FLOATING );   /// Flags
lv_obj_clear_flag( ui_header, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_header, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_header, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_header, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_header, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_header, 20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mobile = lv_label_create(ui_header);
lv_obj_set_width( ui_mobile, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mobile, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mobile, 10 );
lv_obj_set_y( ui_mobile, 7 );
lv_label_set_text(ui_mobile,"中国移动");
lv_obj_clear_flag( ui_mobile, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_mobile, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mobile, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_time = lv_label_create(ui_header);
lv_obj_set_width( ui_time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_time, 0 );
lv_obj_set_y( ui_time, 7 );
lv_obj_set_align( ui_time, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_time,"12:12");
lv_obj_clear_flag( ui_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifi = lv_label_create(ui_header);
lv_obj_set_width( ui_wifi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifi, 78 );
lv_obj_set_y( ui_wifi, 7 );
lv_label_set_text(ui_wifi,"");
lv_obj_clear_flag( ui_wifi, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_wifi, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifi, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifi, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_body = lv_obj_create(ui_home);
lv_obj_set_width( ui_body, lv_pct(100));
lv_obj_set_height( ui_body, lv_pct(80));
lv_obj_set_x( ui_body, lv_pct(0) );
lv_obj_set_y( ui_body, lv_pct(10) );
lv_obj_set_align( ui_body, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_body,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_body, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_body, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ONE );   /// Flags
lv_obj_clear_flag( ui_body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_body, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_body, LV_DIR_HOR);
lv_obj_set_style_radius(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_body, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_body, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_width(ui_body, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_home1 = lv_obj_create(ui_body);
lv_obj_set_width( ui_home1, lv_pct(100));
lv_obj_set_height( ui_home1, lv_pct(100));
lv_obj_set_align( ui_home1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_home1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_home1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_home1, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_home1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_home1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_home1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_home1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_home1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_home1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_home1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpiobtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_gpiobtn, lv_pct(30));
lv_obj_set_height( ui_gpiobtn, lv_pct(30));
lv_obj_set_x( ui_gpiobtn, 108 );
lv_obj_set_y( ui_gpiobtn, 21 );
lv_obj_set_align( ui_gpiobtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_gpiobtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_gpiobtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_gpiobtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_gpiobtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_gpiolabel = lv_label_create(ui_gpiobtn);
lv_obj_set_width( ui_gpiolabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpiolabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpiolabel, 154 );
lv_obj_set_y( ui_gpiolabel, 55 );
lv_obj_set_align( ui_gpiolabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_gpiolabel,"GPIO");

ui_isrbtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_isrbtn, lv_pct(30));
lv_obj_set_height( ui_isrbtn, lv_pct(30));
lv_obj_set_x( ui_isrbtn, 108 );
lv_obj_set_y( ui_isrbtn, 21 );
lv_obj_set_align( ui_isrbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_isrbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_isrbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_isrbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_isrbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_isrlabel = lv_label_create(ui_isrbtn);
lv_obj_set_width( ui_isrlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_isrlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_isrlabel, 154 );
lv_obj_set_y( ui_isrlabel, 55 );
lv_obj_set_align( ui_isrlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_isrlabel,"ISR");

ui_timebtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_timebtn, lv_pct(30));
lv_obj_set_height( ui_timebtn, lv_pct(30));
lv_obj_set_x( ui_timebtn, 108 );
lv_obj_set_y( ui_timebtn, 21 );
lv_obj_set_align( ui_timebtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timebtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_timebtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_timebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_timebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timelabel = lv_label_create(ui_timebtn);
lv_obj_set_width( ui_timelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timelabel, 154 );
lv_obj_set_y( ui_timelabel, 55 );
lv_obj_set_align( ui_timelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_timelabel,"TIMER");

ui_adbtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_adbtn, lv_pct(30));
lv_obj_set_height( ui_adbtn, lv_pct(30));
lv_obj_set_x( ui_adbtn, -170 );
lv_obj_set_y( ui_adbtn, -20 );
lv_obj_set_align( ui_adbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_adbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_adbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_adbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_adbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_adlabel = lv_label_create(ui_adbtn);
lv_obj_set_width( ui_adlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adlabel, 154 );
lv_obj_set_y( ui_adlabel, 55 );
lv_obj_set_align( ui_adlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_adlabel,"ADC");

ui_pwmbtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_pwmbtn, lv_pct(30));
lv_obj_set_height( ui_pwmbtn, lv_pct(30));
lv_obj_set_x( ui_pwmbtn, 618 );
lv_obj_set_y( ui_pwmbtn, 4 );
lv_obj_set_align( ui_pwmbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_pwmbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_pwmbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_pwmbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_pwmbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pwmlabel = lv_label_create(ui_pwmbtn);
lv_obj_set_width( ui_pwmlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pwmlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pwmlabel, 154 );
lv_obj_set_y( ui_pwmlabel, 55 );
lv_obj_set_align( ui_pwmlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pwmlabel,"PWM");

ui_dabtn = lv_btn_create(ui_home1);
lv_obj_set_width( ui_dabtn, lv_pct(30));
lv_obj_set_height( ui_dabtn, lv_pct(30));
lv_obj_set_x( ui_dabtn, 108 );
lv_obj_set_y( ui_dabtn, 21 );
lv_obj_set_align( ui_dabtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_dabtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_dabtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_dabtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_dabtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dalabel = lv_label_create(ui_dabtn);
lv_obj_set_width( ui_dalabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dalabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dalabel, 154 );
lv_obj_set_y( ui_dalabel, 55 );
lv_obj_set_align( ui_dalabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_dalabel,"DAC");

ui_home2 = lv_obj_create(ui_body);
lv_obj_set_width( ui_home2, lv_pct(100));
lv_obj_set_height( ui_home2, lv_pct(100));
lv_obj_set_x( ui_home2, 280 );
lv_obj_set_y( ui_home2, 2 );
lv_obj_set_align( ui_home2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_home2,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_home2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_home2, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_home2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_home2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_home2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_home2, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_home2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_home2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_home2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uartbtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_uartbtn, lv_pct(30));
lv_obj_set_height( ui_uartbtn, lv_pct(30));
lv_obj_set_x( ui_uartbtn, 108 );
lv_obj_set_y( ui_uartbtn, 21 );
lv_obj_set_align( ui_uartbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uartbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_uartbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_uartbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_uartbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uartlabel = lv_label_create(ui_uartbtn);
lv_obj_set_width( ui_uartlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uartlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uartlabel, 154 );
lv_obj_set_y( ui_uartlabel, 55 );
lv_obj_set_align( ui_uartlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_uartlabel,"UART");

ui_i2cbtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_i2cbtn, lv_pct(30));
lv_obj_set_height( ui_i2cbtn, lv_pct(30));
lv_obj_set_x( ui_i2cbtn, 108 );
lv_obj_set_y( ui_i2cbtn, 21 );
lv_obj_set_align( ui_i2cbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_i2cbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_i2cbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_i2cbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_i2cbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_i2clabel = lv_label_create(ui_i2cbtn);
lv_obj_set_width( ui_i2clabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_i2clabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_i2clabel, 154 );
lv_obj_set_y( ui_i2clabel, 55 );
lv_obj_set_align( ui_i2clabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_i2clabel,"I2C");

ui_spibtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_spibtn, lv_pct(30));
lv_obj_set_height( ui_spibtn, lv_pct(30));
lv_obj_set_x( ui_spibtn, 108 );
lv_obj_set_y( ui_spibtn, 21 );
lv_obj_set_align( ui_spibtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_spibtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_spibtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_spibtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_spibtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spilabel = lv_label_create(ui_spibtn);
lv_obj_set_width( ui_spilabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spilabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spilabel, 154 );
lv_obj_set_y( ui_spilabel, 55 );
lv_obj_set_align( ui_spilabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_spilabel,"SPI");

ui_mqttbtn = lv_btn_create(ui_home2);
lv_obj_set_width( ui_mqttbtn, lv_pct(30));
lv_obj_set_height( ui_mqttbtn, lv_pct(30));
lv_obj_set_x( ui_mqttbtn, 108 );
lv_obj_set_y( ui_mqttbtn, 21 );
lv_obj_set_align( ui_mqttbtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mqttbtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_mqttbtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_mqttbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_mqttbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mqttlabel = lv_label_create(ui_mqttbtn);
lv_obj_set_width( ui_mqttlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqttlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mqttlabel, 154 );
lv_obj_set_y( ui_mqttlabel, 55 );
lv_obj_set_align( ui_mqttlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_mqttlabel,"MQTT");

ui_menudown = lv_obj_create(ui_home);
lv_obj_set_width( ui_menudown, lv_pct(100));
lv_obj_set_height( ui_menudown, lv_pct(100));
lv_obj_set_x( ui_menudown, 0 );
lv_obj_set_y( ui_menudown, -240 );
lv_obj_set_align( ui_menudown, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_menudown,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_menudown, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_menudown, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_menudown, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_menudown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_menudown, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_menudown, 250, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menudown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_menudowntop = lv_obj_create(ui_menudown);
lv_obj_set_width( ui_menudowntop, lv_pct(100));
lv_obj_set_height( ui_menudowntop, lv_pct(30));
lv_obj_set_align( ui_menudowntop, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_menudowntop,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_menudowntop, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_menudowntop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_menudowntop, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menudowntop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifibtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_wifibtn, 50);
lv_obj_set_height( ui_wifibtn, 50);
lv_obj_set_align( ui_wifibtn, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_wifibtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifibtn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wifibtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifibtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifibtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifibtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_wifibtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_wifibtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_wifibtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_wifibtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_wifilabel = lv_label_create(ui_wifibtn);
lv_obj_set_width( ui_wifilabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifilabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifilabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifilabel,"");

ui_bluebtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_bluebtn, 50);
lv_obj_set_height( ui_bluebtn, 50);
lv_obj_set_x( ui_bluebtn, 68 );
lv_obj_set_y( ui_bluebtn, 0 );
lv_obj_set_align( ui_bluebtn, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_bluebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_bluebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_bluebtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bluebtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bluebtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_bluebtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_bluebtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_bluebtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_bluebtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_bluebtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_bluelabel = lv_label_create(ui_bluebtn);
lv_obj_set_width( ui_bluelabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bluelabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_bluelabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_bluelabel,"");

ui_gpsbtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_gpsbtn, 50);
lv_obj_set_height( ui_gpsbtn, 50);
lv_obj_set_x( ui_gpsbtn, -68 );
lv_obj_set_y( ui_gpsbtn, 0 );
lv_obj_set_align( ui_gpsbtn, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_gpsbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_gpsbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpsbtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpsbtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpsbtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpsbtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_gpsbtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_gpsbtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_gpsbtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_gpsbtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_mutelabel1 = lv_label_create(ui_gpsbtn);
lv_obj_set_width( ui_mutelabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mutelabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mutelabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_mutelabel1,"");

ui_settinglbtn = lv_btn_create(ui_menudowntop);
lv_obj_set_width( ui_settinglbtn, 50);
lv_obj_set_height( ui_settinglbtn, 50);
lv_obj_set_align( ui_settinglbtn, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_settinglbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_settinglbtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_settinglbtn, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_settinglbtn, lv_color_hex(0xACACAC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settinglbtn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_settinglbtn, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_settinglbtn, 50, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_settinglbtn, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_settinglbtn, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_border_width(ui_settinglbtn, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_settinglabel = lv_label_create(ui_settinglbtn);
lv_obj_set_width( ui_settinglabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settinglabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_settinglabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_settinglabel,"");

ui_lightslider = lv_slider_create(ui_menudown);
lv_slider_set_value( ui_lightslider, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_lightslider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_lightslider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_lightslider, lv_pct(100));
lv_obj_set_height( ui_lightslider, lv_pct(16));
lv_obj_set_align( ui_lightslider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_lightslider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lightslider, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightslider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_lightslider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_lightslider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lightslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightslider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_lightslider, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lightslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lightslider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_lighttext = lv_label_create(ui_lightslider);
lv_obj_set_width( ui_lighttext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lighttext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lighttext, 10 );
lv_obj_set_y( ui_lighttext, 0 );
lv_obj_set_align( ui_lighttext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_lighttext,"");
lv_obj_set_style_text_color(ui_lighttext, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lighttext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lighttext, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_volumeslider = lv_slider_create(ui_menudown);
lv_slider_set_value( ui_volumeslider, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_volumeslider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_volumeslider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_volumeslider, lv_pct(100));
lv_obj_set_height( ui_volumeslider, lv_pct(16));
lv_obj_set_align( ui_volumeslider, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_volumeslider, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_volumeslider, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_volumeslider, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeslider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_volumeslider, 10, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_volumeslider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_volumeslider, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_volumetext = lv_label_create(ui_volumeslider);
lv_obj_set_width( ui_volumetext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_volumetext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_volumetext, 10 );
lv_obj_set_y( ui_volumetext, 0 );
lv_obj_set_align( ui_volumetext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_volumetext,"");
lv_obj_set_style_text_color(ui_volumetext, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_volumetext, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_volumetext, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_menudownfoot = lv_obj_create(ui_menudown);
lv_obj_set_width( ui_menudownfoot, lv_pct(17));
lv_obj_set_height( ui_menudownfoot, lv_pct(1));
lv_obj_set_x( ui_menudownfoot, 0 );
lv_obj_set_y( ui_menudownfoot, lv_pct(100) );
lv_obj_set_align( ui_menudownfoot, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_menudownfoot, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_menudownfoot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_menudownfoot, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_menudownfoot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_menudownfoot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpiolayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_gpiolayer, lv_pct(100));
lv_obj_set_height( ui_gpiolayer, lv_pct(100));
lv_obj_set_x( ui_gpiolayer, 0 );
lv_obj_set_y( ui_gpiolayer, -240 );
lv_obj_set_align( ui_gpiolayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_gpiolayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_gpiolayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_gpiolayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_gpiolayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpiolayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpiolayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpiolayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpiolayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpioheader = lv_obj_create(ui_gpiolayer);
lv_obj_set_width( ui_gpioheader, lv_pct(100));
lv_obj_set_height( ui_gpioheader, lv_pct(20));
lv_obj_set_x( ui_gpioheader, lv_pct(0) );
lv_obj_set_y( ui_gpioheader, lv_pct(-8) );
lv_obj_set_align( ui_gpioheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_gpioheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_gpioheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_gpioheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpioheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpioheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_gpioheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_gpioheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpioheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_gpioheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_gpioheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_gpioheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gpioheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpioheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wlantitle2 = lv_label_create(ui_gpioheader);
lv_obj_set_width( ui_wlantitle2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wlantitle2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wlantitle2, 30 );
lv_obj_set_y( ui_wlantitle2, -2 );
lv_obj_set_align( ui_wlantitle2, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_wlantitle2,"GPIO实验");

ui_gpiopanel = lv_obj_create(ui_gpiolayer);
lv_obj_set_width( ui_gpiopanel, lv_pct(100));
lv_obj_set_height( ui_gpiopanel, lv_pct(80));
lv_obj_set_x( ui_gpiopanel, lv_pct(-30) );
lv_obj_set_y( ui_gpiopanel, lv_pct(0) );
lv_obj_set_align( ui_gpiopanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_gpiopanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gpiopanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gpiopanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gpiopanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_gpiopanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_led = lv_btn_create(ui_gpiopanel);
lv_obj_set_width( ui_led, 100);
lv_obj_set_height( ui_led, 50);
lv_obj_set_x( ui_led, 4 );
lv_obj_set_y( ui_led, 13 );
lv_obj_set_align( ui_led, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_led, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_led, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_isrlayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_isrlayer, lv_pct(100));
lv_obj_set_height( ui_isrlayer, lv_pct(100));
lv_obj_set_x( ui_isrlayer, 0 );
lv_obj_set_y( ui_isrlayer, -240 );
lv_obj_set_align( ui_isrlayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_isrlayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_isrlayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_isrlayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_isrlayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_isrlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_isrlayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_isrlayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_isrlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_isrheader = lv_obj_create(ui_isrlayer);
lv_obj_set_width( ui_isrheader, lv_pct(100));
lv_obj_set_height( ui_isrheader, lv_pct(20));
lv_obj_set_x( ui_isrheader, lv_pct(0) );
lv_obj_set_y( ui_isrheader, lv_pct(-8) );
lv_obj_set_align( ui_isrheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_isrheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_isrheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_isrheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_isrheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_isrheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_isrheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_isrheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_isrheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_isrheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_isrheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_isrheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_isrheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_isrheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_isrheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_isrheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_isrheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_isrheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_isrtitle = lv_label_create(ui_isrheader);
lv_obj_set_width( ui_isrtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_isrtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_isrtitle, 30 );
lv_obj_set_y( ui_isrtitle, -2 );
lv_obj_set_align( ui_isrtitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_isrtitle,"中断实验");

ui_isrpanel = lv_obj_create(ui_isrlayer);
lv_obj_set_width( ui_isrpanel, lv_pct(100));
lv_obj_set_height( ui_isrpanel, lv_pct(80));
lv_obj_set_x( ui_isrpanel, lv_pct(0) );
lv_obj_set_y( ui_isrpanel, lv_pct(13) );
lv_obj_set_align( ui_isrpanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_isrpanel,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_isrpanel, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_isrpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_isrpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_isrpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_isrpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_isrpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_isrbtn0 = lv_btn_create(ui_isrpanel);
lv_obj_set_width( ui_isrbtn0, lv_pct(30));
lv_obj_set_height( ui_isrbtn0, lv_pct(30));
lv_obj_set_x( ui_isrbtn0, 108 );
lv_obj_set_y( ui_isrbtn0, 21 );
lv_obj_set_align( ui_isrbtn0, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_isrbtn0,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_isrbtn0, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_isrbtn0, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_isrbtn0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_isrlabel0 = lv_label_create(ui_isrbtn0);
lv_obj_set_width( ui_isrlabel0, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_isrlabel0, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_isrlabel0, 154 );
lv_obj_set_y( ui_isrlabel0, 55 );
lv_obj_set_align( ui_isrlabel0, LV_ALIGN_CENTER );
lv_label_set_text(ui_isrlabel0,"上升沿");

ui_isrbtn1 = lv_btn_create(ui_isrpanel);
lv_obj_set_width( ui_isrbtn1, lv_pct(30));
lv_obj_set_height( ui_isrbtn1, lv_pct(30));
lv_obj_set_x( ui_isrbtn1, 108 );
lv_obj_set_y( ui_isrbtn1, 21 );
lv_obj_set_align( ui_isrbtn1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_isrbtn1,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_isrbtn1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_isrbtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_isrbtn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_isrlabel1 = lv_label_create(ui_isrbtn1);
lv_obj_set_width( ui_isrlabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_isrlabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_isrlabel1, 154 );
lv_obj_set_y( ui_isrlabel1, 55 );
lv_obj_set_align( ui_isrlabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_isrlabel1,"下降沿");

ui_isrbtn2 = lv_btn_create(ui_isrpanel);
lv_obj_set_width( ui_isrbtn2, lv_pct(30));
lv_obj_set_height( ui_isrbtn2, lv_pct(30));
lv_obj_set_x( ui_isrbtn2, 108 );
lv_obj_set_y( ui_isrbtn2, 21 );
lv_obj_set_align( ui_isrbtn2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_isrbtn2,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_isrbtn2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_isrbtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_isrbtn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_isrlabel2 = lv_label_create(ui_isrbtn2);
lv_obj_set_width( ui_isrlabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_isrlabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_isrlabel2, 154 );
lv_obj_set_y( ui_isrlabel2, 55 );
lv_obj_set_align( ui_isrlabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_isrlabel2,"任意沿");

ui_timelayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_timelayer, lv_pct(100));
lv_obj_set_height( ui_timelayer, lv_pct(100));
lv_obj_set_x( ui_timelayer, 0 );
lv_obj_set_y( ui_timelayer, -240 );
lv_obj_set_align( ui_timelayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_timelayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timelayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_timelayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_timelayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_timelayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_timelayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_timelayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_timelayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timerheader = lv_obj_create(ui_timelayer);
lv_obj_set_width( ui_timerheader, lv_pct(100));
lv_obj_set_height( ui_timerheader, lv_pct(20));
lv_obj_set_x( ui_timerheader, lv_pct(0) );
lv_obj_set_y( ui_timerheader, lv_pct(-8) );
lv_obj_set_align( ui_timerheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_timerheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_timerheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_timerheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_timerheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_timerheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_timerheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_timerheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_timerheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_timerheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_timerheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timerheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timerheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timertitel = lv_label_create(ui_timerheader);
lv_obj_set_width( ui_timertitel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timertitel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timertitel, 30 );
lv_obj_set_y( ui_timertitel, -2 );
lv_obj_set_align( ui_timertitel, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_timertitel,"定时器实验");

ui_timerpanel = lv_obj_create(ui_timelayer);
lv_obj_set_width( ui_timerpanel, lv_pct(100));
lv_obj_set_height( ui_timerpanel, lv_pct(80));
lv_obj_set_x( ui_timerpanel, lv_pct(0) );
lv_obj_set_y( ui_timerpanel, lv_pct(13) );
lv_obj_set_align( ui_timerpanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_timerpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_timerpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_timerpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_timerpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_timerpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeBox = lv_spinbox_create(ui_timerpanel);
lv_obj_set_width( ui_timeBox, 70);
lv_obj_set_height( ui_timeBox, 42);
lv_obj_set_align( ui_timeBox, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_timeBox, 4, 2);
lv_spinbox_set_range( ui_timeBox, 0,9999 );
lv_spinbox_set_step( ui_timeBox, round(pow(10, 1 - 1)) );

ui_adlayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_adlayer, lv_pct(100));
lv_obj_set_height( ui_adlayer, lv_pct(100));
lv_obj_set_x( ui_adlayer, 0 );
lv_obj_set_y( ui_adlayer, -240 );
lv_obj_set_align( ui_adlayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_adlayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_adlayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_adlayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_adlayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_adlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_adlayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adlayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_adlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adheader = lv_obj_create(ui_adlayer);
lv_obj_set_width( ui_adheader, lv_pct(100));
lv_obj_set_height( ui_adheader, lv_pct(20));
lv_obj_set_x( ui_adheader, lv_pct(0) );
lv_obj_set_y( ui_adheader, lv_pct(-8) );
lv_obj_set_align( ui_adheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_adheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_adheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_adheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_adheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_adheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_adheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_adheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_adheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_adheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_adheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_adheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_adheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_adheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_adheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_adheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_adheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adtitle = lv_label_create(ui_adheader);
lv_obj_set_width( ui_adtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adtitle, 30 );
lv_obj_set_y( ui_adtitle, -2 );
lv_obj_set_align( ui_adtitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_adtitle,"ADC实验");

ui_adpanel = lv_obj_create(ui_adlayer);
lv_obj_set_width( ui_adpanel, lv_pct(100));
lv_obj_set_height( ui_adpanel, lv_pct(80));
lv_obj_set_x( ui_adpanel, lv_pct(0) );
lv_obj_set_y( ui_adpanel, lv_pct(13) );
lv_obj_set_align( ui_adpanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_adpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_adpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_adpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_adpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_adpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_adArc = lv_arc_create(ui_adpanel);
lv_obj_set_width( ui_adArc, 150);
lv_obj_set_height( ui_adArc, 150);
lv_obj_set_align( ui_adArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_adArc, 0,360);
lv_arc_set_value(ui_adArc, 80);
lv_arc_set_bg_angles(ui_adArc,0,360);
lv_arc_set_rotation(ui_adArc,180);


ui_pwmlayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_pwmlayer, lv_pct(100));
lv_obj_set_height( ui_pwmlayer, lv_pct(100));
lv_obj_set_x( ui_pwmlayer, 0 );
lv_obj_set_y( ui_pwmlayer, -240 );
lv_obj_set_align( ui_pwmlayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_pwmlayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_pwmlayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_pwmlayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_pwmlayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pwmlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_pwmlayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pwmlayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_pwmlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pwmheader = lv_obj_create(ui_pwmlayer);
lv_obj_set_width( ui_pwmheader, lv_pct(100));
lv_obj_set_height( ui_pwmheader, lv_pct(20));
lv_obj_set_x( ui_pwmheader, lv_pct(0) );
lv_obj_set_y( ui_pwmheader, lv_pct(-8) );
lv_obj_set_align( ui_pwmheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_pwmheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_pwmheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_pwmheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pwmheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_pwmheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pwmheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_pwmheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_pwmheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_pwmheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_pwmheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_pwmheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pwmheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pwmheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pwmheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_pwmheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pwmheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pwmheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pwmtitle = lv_label_create(ui_pwmheader);
lv_obj_set_width( ui_pwmtitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pwmtitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pwmtitle, 30 );
lv_obj_set_y( ui_pwmtitle, -2 );
lv_obj_set_align( ui_pwmtitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_pwmtitle,"PWM实验");

ui_pwmpanel = lv_obj_create(ui_pwmlayer);
lv_obj_set_width( ui_pwmpanel, lv_pct(100));
lv_obj_set_height( ui_pwmpanel, lv_pct(80));
lv_obj_set_x( ui_pwmpanel, lv_pct(0) );
lv_obj_set_y( ui_pwmpanel, lv_pct(13) );
lv_obj_set_align( ui_pwmpanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_pwmpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pwmpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_pwmpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pwmpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_pwmpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pwm = lv_btn_create(ui_pwmpanel);
lv_obj_set_width( ui_pwm, 100);
lv_obj_set_height( ui_pwm, 50);
lv_obj_set_align( ui_pwm, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pwm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_pwm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dalayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_dalayer, lv_pct(100));
lv_obj_set_height( ui_dalayer, lv_pct(100));
lv_obj_set_x( ui_dalayer, 0 );
lv_obj_set_y( ui_dalayer, -240 );
lv_obj_set_align( ui_dalayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_dalayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_dalayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_dalayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_dalayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_dalayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dalayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dalayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dalayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_daheeader = lv_obj_create(ui_dalayer);
lv_obj_set_width( ui_daheeader, lv_pct(100));
lv_obj_set_height( ui_daheeader, lv_pct(20));
lv_obj_set_x( ui_daheeader, lv_pct(0) );
lv_obj_set_y( ui_daheeader, lv_pct(-8) );
lv_obj_set_align( ui_daheeader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_daheeader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_daheeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_daheeader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_daheeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_daheeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_daheeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_daheeader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_daheeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_daheeader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_daheeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_daheeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_daheeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_daheeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_daheeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_daheeader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_daheeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_daheeader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_datitle = lv_label_create(ui_daheeader);
lv_obj_set_width( ui_datitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_datitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_datitle, 30 );
lv_obj_set_y( ui_datitle, -2 );
lv_obj_set_align( ui_datitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_datitle,"DAC实验");

ui_dapanel = lv_obj_create(ui_dalayer);
lv_obj_set_width( ui_dapanel, lv_pct(100));
lv_obj_set_height( ui_dapanel, lv_pct(80));
lv_obj_set_x( ui_dapanel, lv_pct(0) );
lv_obj_set_y( ui_dapanel, lv_pct(13) );
lv_obj_set_align( ui_dapanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_dapanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_dapanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_dapanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dapanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_dapanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dachart = lv_chart_create(ui_dapanel);
lv_obj_set_width( ui_dachart, 200);
lv_obj_set_height( ui_dachart, 100);
lv_obj_set_x( ui_dachart, 17 );
lv_obj_set_y( ui_dachart, -7 );
lv_obj_set_align( ui_dachart, LV_ALIGN_RIGHT_MID );
lv_chart_set_type( ui_dachart, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_dachart, LV_CHART_AXIS_PRIMARY_Y, 0, 5000);
lv_chart_set_range( ui_dachart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
lv_chart_set_div_line_count( ui_dachart, 10, 20);
lv_chart_set_axis_tick( ui_dachart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 10, 2, true, 50);
lv_chart_set_axis_tick( ui_dachart, LV_CHART_AXIS_PRIMARY_Y, 7, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_dachart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
lv_chart_series_t* ui_dachart_series_1 = lv_chart_add_series(ui_dachart, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_dachart_series_1_array[] = { 0,10,2000,40,80,80,4000,20,4800,0,0 };
lv_chart_set_ext_y_array(ui_dachart, ui_dachart_series_1, ui_dachart_series_1_array);



ui_uartlayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_uartlayer, lv_pct(100));
lv_obj_set_height( ui_uartlayer, lv_pct(100));
lv_obj_set_x( ui_uartlayer, 0 );
lv_obj_set_y( ui_uartlayer, -240 );
lv_obj_set_align( ui_uartlayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_uartlayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_uartlayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_uartlayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_uartlayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uartlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_uartlayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uartlayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_uartlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uartheader = lv_obj_create(ui_uartlayer);
lv_obj_set_width( ui_uartheader, lv_pct(100));
lv_obj_set_height( ui_uartheader, lv_pct(20));
lv_obj_set_x( ui_uartheader, lv_pct(0) );
lv_obj_set_y( ui_uartheader, lv_pct(-8) );
lv_obj_set_align( ui_uartheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_uartheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_uartheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_uartheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_uartheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uartheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_uartheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_uartheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_uartheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_uartheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_uartheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uartheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uartheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uarttitle = lv_label_create(ui_uartheader);
lv_obj_set_width( ui_uarttitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uarttitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uarttitle, 30 );
lv_obj_set_y( ui_uarttitle, -2 );
lv_obj_set_align( ui_uarttitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_uarttitle,"UART实验");

ui_uartpanel = lv_obj_create(ui_uartlayer);
lv_obj_set_width( ui_uartpanel, lv_pct(100));
lv_obj_set_height( ui_uartpanel, lv_pct(80));
lv_obj_set_x( ui_uartpanel, lv_pct(-30) );
lv_obj_set_y( ui_uartpanel, lv_pct(0) );
lv_obj_set_align( ui_uartpanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_uartpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uartpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_uartpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uartpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_uartpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uart = lv_btn_create(ui_uartpanel);
lv_obj_set_width( ui_uart, 100);
lv_obj_set_height( ui_uart, 50);
lv_obj_set_align( ui_uart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_uart, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_uart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_i2clayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_i2clayer, lv_pct(100));
lv_obj_set_height( ui_i2clayer, lv_pct(100));
lv_obj_set_x( ui_i2clayer, 0 );
lv_obj_set_y( ui_i2clayer, -240 );
lv_obj_set_align( ui_i2clayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_i2clayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_i2clayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_i2clayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_i2clayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_i2clayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_i2clayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_i2clayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_i2clayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_i2cheader = lv_obj_create(ui_i2clayer);
lv_obj_set_width( ui_i2cheader, lv_pct(100));
lv_obj_set_height( ui_i2cheader, lv_pct(20));
lv_obj_set_x( ui_i2cheader, lv_pct(0) );
lv_obj_set_y( ui_i2cheader, lv_pct(-8) );
lv_obj_set_align( ui_i2cheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_i2cheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_i2cheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_i2cheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_i2cheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_i2cheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_i2cheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_i2cheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_i2cheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_i2cheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_i2cheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_i2cheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_i2cheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_i2cheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_i2cheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_i2cheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_i2cheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_i2cheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_i2ctitle = lv_label_create(ui_i2cheader);
lv_obj_set_width( ui_i2ctitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_i2ctitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_i2ctitle, 30 );
lv_obj_set_y( ui_i2ctitle, -2 );
lv_obj_set_align( ui_i2ctitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_i2ctitle,"I2C实验");

ui_i2cpanel = lv_obj_create(ui_i2clayer);
lv_obj_set_width( ui_i2cpanel, lv_pct(100));
lv_obj_set_height( ui_i2cpanel, lv_pct(80));
lv_obj_set_x( ui_i2cpanel, lv_pct(-30) );
lv_obj_set_y( ui_i2cpanel, lv_pct(0) );
lv_obj_set_align( ui_i2cpanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_i2cpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_i2cpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_i2cpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_i2cpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_i2cpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_i2c = lv_btn_create(ui_i2cpanel);
lv_obj_set_width( ui_i2c, 100);
lv_obj_set_height( ui_i2c, 50);
lv_obj_set_align( ui_i2c, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_i2c, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_i2c, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spilayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_spilayer, lv_pct(100));
lv_obj_set_height( ui_spilayer, lv_pct(100));
lv_obj_set_x( ui_spilayer, 0 );
lv_obj_set_y( ui_spilayer, -240 );
lv_obj_set_align( ui_spilayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_spilayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_spilayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_spilayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_spilayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_spilayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_spilayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_spilayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_spilayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_spiheader = lv_obj_create(ui_spilayer);
lv_obj_set_width( ui_spiheader, lv_pct(100));
lv_obj_set_height( ui_spiheader, lv_pct(20));
lv_obj_set_x( ui_spiheader, lv_pct(0) );
lv_obj_set_y( ui_spiheader, lv_pct(-8) );
lv_obj_set_align( ui_spiheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_spiheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_spiheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_spiheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_spiheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_spiheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_spiheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_spiheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_spiheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_spiheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_spiheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_spiheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_spiheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_spititle = lv_label_create(ui_spiheader);
lv_obj_set_width( ui_spititle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spititle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spititle, 30 );
lv_obj_set_y( ui_spititle, -2 );
lv_obj_set_align( ui_spititle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_spititle,"SPI实验");

ui_spipanel = lv_obj_create(ui_spilayer);
lv_obj_set_width( ui_spipanel, lv_pct(100));
lv_obj_set_height( ui_spipanel, lv_pct(80));
lv_obj_set_x( ui_spipanel, lv_pct(-30) );
lv_obj_set_y( ui_spipanel, lv_pct(0) );
lv_obj_set_align( ui_spipanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_spipanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_spipanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_spipanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_spipanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_spipanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_spi = lv_btn_create(ui_spipanel);
lv_obj_set_width( ui_spi, 100);
lv_obj_set_height( ui_spi, 50);
lv_obj_set_align( ui_spi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_spi, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_spi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mqttlayer = lv_obj_create(ui_home);
lv_obj_set_width( ui_mqttlayer, lv_pct(100));
lv_obj_set_height( ui_mqttlayer, lv_pct(100));
lv_obj_set_x( ui_mqttlayer, 0 );
lv_obj_set_y( ui_mqttlayer, -240 );
lv_obj_set_align( ui_mqttlayer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mqttlayer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_mqttlayer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_mqttlayer, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_clear_flag( ui_mqttlayer, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mqttlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mqttlayer, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqttlayer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mqttlayer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqttheader = lv_obj_create(ui_mqttlayer);
lv_obj_set_width( ui_mqttheader, lv_pct(100));
lv_obj_set_height( ui_mqttheader, lv_pct(20));
lv_obj_set_x( ui_mqttheader, lv_pct(0) );
lv_obj_set_y( ui_mqttheader, lv_pct(-8) );
lv_obj_set_align( ui_mqttheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_mqttheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mqttheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_mqttheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mqttheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mqttheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqttheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mqttheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mqttheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mqttheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_mqttheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_mqttheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_mqttheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_mqttheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_mqttheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_mqttheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mqttheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mqttheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqtttitle = lv_label_create(ui_mqttheader);
lv_obj_set_width( ui_mqtttitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mqtttitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mqtttitle, 30 );
lv_obj_set_y( ui_mqtttitle, -2 );
lv_obj_set_align( ui_mqtttitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_mqtttitle,"MQTT实验");

ui_mqttpanel = lv_obj_create(ui_mqttlayer);
lv_obj_set_width( ui_mqttpanel, lv_pct(100));
lv_obj_set_height( ui_mqttpanel, lv_pct(80));
lv_obj_set_x( ui_mqttpanel, lv_pct(-30) );
lv_obj_set_y( ui_mqttpanel, lv_pct(0) );
lv_obj_set_align( ui_mqttpanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_mqttpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_mqttpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mqttpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mqttpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mqttpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mqtt = lv_btn_create(ui_mqttpanel);
lv_obj_set_width( ui_mqtt, 100);
lv_obj_set_height( ui_mqtt, 50);
lv_obj_set_align( ui_mqtt, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_mqtt, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_mqtt, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_header, ui_event_header, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_gpiobtn, ui_event_gpiobtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_isrbtn, ui_event_isrbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_timebtn, ui_event_timebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adbtn, ui_event_adbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pwmbtn, ui_event_pwmbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dabtn, ui_event_dabtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uartbtn, ui_event_uartbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_i2cbtn, ui_event_i2cbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spibtn, ui_event_spibtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mqttbtn, ui_event_mqttbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifibtn, ui_event_wifibtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bluebtn, ui_event_bluebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_gpsbtn, ui_event_gpsbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_settinglbtn, ui_event_settinglbtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_lightslider, ui_event_lightslider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_volumeslider, ui_event_volumeslider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_menudown, ui_event_menudown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_led, ui_event_led, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_gpiolayer, ui_event_gpiolayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_isrbtn0, ui_event_isrbtn0, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_isrbtn1, ui_event_isrbtn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_isrbtn2, ui_event_isrbtn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_isrlayer, ui_event_isrlayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_timeBox, ui_event_timeBox, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_timelayer, ui_event_timelayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adArc, ui_event_adArc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_adlayer, ui_event_adlayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pwm, ui_event_pwm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_pwmlayer, ui_event_pwmlayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dachart, ui_event_dachart, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dalayer, ui_event_dalayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uart, ui_event_uart, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uartlayer, ui_event_uartlayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_i2c, ui_event_i2c, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_i2clayer, ui_event_i2clayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spi, ui_event_spi, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spilayer, ui_event_spilayer, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mqtt, ui_event_mqtt, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_mqttlayer, ui_event_mqttlayer, LV_EVENT_ALL, NULL);

}
