// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_pwmui_screen_init(void)
{
    ui_pwmui = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_pwmui, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_pwmheader = lv_obj_create(ui_pwmui);
    lv_obj_set_width(ui_pwmheader, lv_pct(100));
    lv_obj_set_height(ui_pwmheader, lv_pct(20));
    lv_obj_set_align(ui_pwmheader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pwmheader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pwmheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pwmheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_pwmheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pwmheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pwmheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pwmheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pwmheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pwmheader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_pwmheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_pwmheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_pwmheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_pwmheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_pwmheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_pwmheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_pwmheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_pwmheader, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwmtitle = lv_label_create(ui_pwmheader);
    lv_obj_set_width(ui_pwmtitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_pwmtitle, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_pwmtitle, 30);
    lv_obj_set_y(ui_pwmtitle, -2);
    lv_obj_set_align(ui_pwmtitle, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_pwmtitle, "PWM实验");

    ui_pwmpanel = lv_obj_create(ui_pwmui);
    lv_obj_set_width(ui_pwmpanel, lv_pct(100));
    lv_obj_set_height(ui_pwmpanel, lv_pct(80));
    lv_obj_set_x(ui_pwmpanel, lv_pct(0));
    lv_obj_set_y(ui_pwmpanel, lv_pct(20));
    lv_obj_set_align(ui_pwmpanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_pwmpanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pwmpanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_pwmpanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_scrollbar_mode(ui_pwmpanel, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_radius(ui_pwmpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_pwmpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pwmpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_pwmpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwmchart = lv_chart_create(ui_pwmpanel);
    lv_obj_set_width(ui_pwmchart, lv_pct(100));
    lv_obj_set_height(ui_pwmchart, lv_pct(100));
    lv_obj_set_x(ui_pwmchart, 37);
    lv_obj_set_y(ui_pwmchart, -6);
    lv_obj_set_align(ui_pwmchart, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_pwmchart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_pwmchart, 96);
    lv_chart_set_range(ui_pwmchart, LV_CHART_AXIS_PRIMARY_Y, 0, 4095);
    lv_chart_set_range(ui_pwmchart, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_pwmchart, 20, 40);
    lv_chart_set_axis_tick(ui_pwmchart, LV_CHART_AXIS_PRIMARY_X, 7, 5, 20, 2, false, 50);
    lv_chart_set_axis_tick(ui_pwmchart, LV_CHART_AXIS_PRIMARY_Y, 5, 2, 10, 2, true, 20);
    lv_chart_set_axis_tick(ui_pwmchart, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);

    lv_obj_add_event_cb(ui_pwmchart, ui_event_pwmchart, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_pwmui, ui_event_pwmui, LV_EVENT_ALL, NULL);
}
