// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_spiui_screen_init(void)
{
ui_spiui = lv_obj_create(NULL);
lv_obj_clear_flag( ui_spiui, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spiheader = lv_obj_create(ui_spiui);
lv_obj_set_width( ui_spiheader, lv_pct(100));
lv_obj_set_height( ui_spiheader, lv_pct(20));
lv_obj_set_align( ui_spiheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_spiheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_spiheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_spiheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_spiheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_spiheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_spiheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_spiheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_spiheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_spiheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_spiheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_spiheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_spiheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_spiheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_spititle = lv_label_create(ui_spiheader);
lv_obj_set_width( ui_spititle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spititle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spititle, 30 );
lv_obj_set_y( ui_spititle, -2 );
lv_obj_set_align( ui_spititle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_spititle,"SPI实验");

ui_spitxpanel = lv_obj_create(ui_spiui);
lv_obj_set_width( ui_spitxpanel, lv_pct(100));
lv_obj_set_height( ui_spitxpanel, lv_pct(15));
lv_obj_set_x( ui_spitxpanel, lv_pct(0) );
lv_obj_set_y( ui_spitxpanel, lv_pct(20) );
lv_obj_set_align( ui_spitxpanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_spitxpanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_spitxpanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_spitxpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spitxlabel = lv_label_create(ui_spitxpanel);
lv_obj_set_width( ui_spitxlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spitxlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spitxlabel, -87 );
lv_obj_set_y( ui_spitxlabel, -33 );
lv_obj_set_align( ui_spitxlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_spitxlabel,"TX");

ui_spitxtext = lv_textarea_create(ui_spitxpanel);
lv_obj_set_width( ui_spitxtext, lv_pct(95));
lv_obj_set_height( ui_spitxtext, LV_SIZE_CONTENT);   /// 460
lv_obj_set_align( ui_spitxtext, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_spitxtext,"Placeholder...");
lv_textarea_set_one_line(ui_spitxtext,true);



ui_spirxpanel = lv_obj_create(ui_spiui);
lv_obj_set_width( ui_spirxpanel, lv_pct(100));
lv_obj_set_height( ui_spirxpanel, lv_pct(15));
lv_obj_set_x( ui_spirxpanel, lv_pct(0) );
lv_obj_set_y( ui_spirxpanel, lv_pct(35) );
lv_obj_set_align( ui_spirxpanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_spirxpanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_spirxpanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_spirxpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spirxlabel = lv_label_create(ui_spirxpanel);
lv_obj_set_width( ui_spirxlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spirxlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spirxlabel, -87 );
lv_obj_set_y( ui_spirxlabel, -33 );
lv_obj_set_align( ui_spirxlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_spirxlabel,"RX");

ui_spirxtext = lv_textarea_create(ui_spirxpanel);
lv_obj_set_width( ui_spirxtext, lv_pct(95));
lv_obj_set_height( ui_spirxtext, LV_SIZE_CONTENT);   /// 460
lv_obj_set_align( ui_spirxtext, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_spirxtext,"Placeholder...");
lv_textarea_set_one_line(ui_spirxtext,true);



ui_spikeyboard = lv_keyboard_create(ui_spiui);
lv_obj_set_width( ui_spikeyboard, lv_pct(100));
lv_obj_set_height( ui_spikeyboard, lv_pct(50));
lv_obj_set_x( ui_spikeyboard, lv_pct(0) );
lv_obj_set_y( ui_spikeyboard, lv_pct(50) );
lv_obj_set_align( ui_spikeyboard, LV_ALIGN_TOP_MID );

ui_spipanel = lv_obj_create(ui_spiui);
lv_obj_set_width( ui_spipanel, lv_pct(100));
lv_obj_set_height( ui_spipanel, lv_pct(80));
lv_obj_set_y( ui_spipanel, 288 );
lv_obj_set_x( ui_spipanel, lv_pct(0) );
lv_obj_set_align( ui_spipanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_spipanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spimastebtn = lv_btn_create(ui_spipanel);
lv_obj_set_width( ui_spimastebtn, lv_pct(30));
lv_obj_set_height( ui_spimastebtn, lv_pct(30));
lv_obj_set_align( ui_spimastebtn, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_spimastebtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_spimastebtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_spimastebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_spimastebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spimasterbtnlabel = lv_label_create(ui_spimastebtn);
lv_obj_set_width( ui_spimasterbtnlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spimasterbtnlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spimasterbtnlabel, 153 );
lv_obj_set_y( ui_spimasterbtnlabel, 55 );
lv_obj_set_align( ui_spimasterbtnlabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_spimasterbtnlabel,"master");

ui_spislavebtn = lv_btn_create(ui_spipanel);
lv_obj_set_width( ui_spislavebtn, lv_pct(30));
lv_obj_set_height( ui_spislavebtn, lv_pct(30));
lv_obj_set_align( ui_spislavebtn, LV_ALIGN_RIGHT_MID );
lv_obj_set_flex_flow(ui_spislavebtn,LV_FLEX_FLOW_COLUMN_WRAP);
lv_obj_set_flex_align(ui_spislavebtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_spislavebtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_spislavebtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_spislavebtnlabel = lv_label_create(ui_spislavebtn);
lv_obj_set_width( ui_spislavebtnlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_spislavebtnlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_spislavebtnlabel, 154 );
lv_obj_set_y( ui_spislavebtnlabel, 55 );
lv_obj_set_align( ui_spislavebtnlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_spislavebtnlabel,"slave");

lv_obj_add_event_cb(ui_spitxtext, ui_event_spitxtext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spirxtext, ui_event_spirxtext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spikeyboard, ui_event_spikeyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spimastebtn, ui_event_spimastebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spislavebtn, ui_event_spislavebtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_spiui, ui_event_spiui, LV_EVENT_ALL, NULL);

}
