// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_setting_screen_init(void)
{
ui_setting = lv_obj_create(NULL);
lv_obj_clear_flag( ui_setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_setting,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_setting, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_radius(ui_setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_setting, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingheader = lv_obj_create(ui_setting);
lv_obj_set_width( ui_settingheader, lv_pct(100));
lv_obj_set_height( ui_settingheader, lv_pct(20));
lv_obj_set_align( ui_settingheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_settingheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_settingheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_settingheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_settingheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_settingheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_settingheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_settingheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_settingheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_settingheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_settingheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_settingheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_settingheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_settingheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_settingheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_settingheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_settingheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_settingheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_settingtext = lv_label_create(ui_settingheader);
lv_obj_set_width( ui_settingtext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_settingtext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_settingtext, 0 );
lv_obj_set_y( ui_settingtext, -2 );
lv_obj_set_align( ui_settingtext, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_settingtext,"设置");

ui_setpannel = lv_obj_create(ui_setting);
lv_obj_set_width( ui_setpannel, lv_pct(100));
lv_obj_set_height( ui_setpannel, lv_pct(80));
lv_obj_set_x( ui_setpannel, lv_pct(0) );
lv_obj_set_y( ui_setpannel, lv_pct(10) );
lv_obj_set_align( ui_setpannel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_setpannel,LV_FLEX_FLOW_COLUMN_REVERSE);
lv_obj_set_flex_align(ui_setpannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_setpannel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_setpannel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_setpannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_setpannel, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_setpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aboutpannel = lv_obj_create(ui_setpannel);
lv_obj_set_width( ui_aboutpannel, lv_pct(100));
lv_obj_set_height( ui_aboutpannel, lv_pct(20));
lv_obj_set_align( ui_aboutpannel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_aboutpannel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_aboutpannel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_aboutpannel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_aboutpannel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_aboutpannel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_aboutpannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_aboutpannel, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_aboutpannel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_aboutpannel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_aboutpannel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aboutlabel = lv_label_create(ui_aboutpannel);
lv_obj_set_width( ui_aboutlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aboutlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aboutlabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_aboutlabel,"关于本机");
lv_obj_clear_flag( ui_aboutlabel, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags

ui_aboutlabel2 = lv_label_create(ui_aboutpannel);
lv_obj_set_width( ui_aboutlabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aboutlabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aboutlabel2, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_aboutlabel2,"");
lv_obj_clear_flag( ui_aboutlabel2, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_color(ui_aboutlabel2, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_aboutlabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_aboutlabel2, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifipanel = lv_obj_create(ui_setpannel);
lv_obj_set_width( ui_wifipanel, lv_pct(100));
lv_obj_set_height( ui_wifipanel, lv_pct(20));
lv_obj_set_align( ui_wifipanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_wifipanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifipanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_wifipanel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_wifipanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_wifipanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_wifipanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_wifipanel, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_wifipanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_wifipanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_wifipanel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifitext = lv_label_create(ui_wifipanel);
lv_obj_set_width( ui_wifitext, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifitext, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifitext, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_wifitext,"WIFI");
lv_obj_clear_flag( ui_wifitext, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags

ui_wifionlabel1 = lv_label_create(ui_wifipanel);
lv_obj_set_width( ui_wifionlabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifionlabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifionlabel1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_wifionlabel1,"");
lv_obj_clear_flag( ui_wifionlabel1, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_color(ui_wifionlabel1, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_wifionlabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_wifionlabel1, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aboutpannel1 = lv_obj_create(ui_setpannel);
lv_obj_set_width( ui_aboutpannel1, lv_pct(100));
lv_obj_set_height( ui_aboutpannel1, lv_pct(20));
lv_obj_set_x( ui_aboutpannel1, 166 );
lv_obj_set_y( ui_aboutpannel1, 2 );
lv_obj_set_align( ui_aboutpannel1, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_aboutpannel1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_aboutpannel1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_aboutpannel1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_aboutpannel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_aboutpannel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_aboutpannel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_aboutpannel1, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_aboutpannel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_aboutpannel1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_aboutpannel1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_aboutlabel19 = lv_label_create(ui_aboutpannel1);
lv_obj_set_width( ui_aboutlabel19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aboutlabel19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aboutlabel19, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_aboutlabel19,"日期和时间");
lv_obj_clear_flag( ui_aboutlabel19, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags

ui_aboutlabel21 = lv_label_create(ui_aboutpannel1);
lv_obj_set_width( ui_aboutlabel21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aboutlabel21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aboutlabel21, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_aboutlabel21,"");
lv_obj_clear_flag( ui_aboutlabel21, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_color(ui_aboutlabel21, lv_color_hex(0x787878), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_aboutlabel21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_aboutlabel21, &ui_font_symbols16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_wifipanel, ui_event_wifipanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_aboutpannel1, ui_event_aboutpannel1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);

}
