// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_timeui_screen_init(void)
{
ui_timeui = lv_obj_create(NULL);
lv_obj_clear_flag( ui_timeui, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_timerheader = lv_obj_create(ui_timeui);
lv_obj_set_width( ui_timerheader, lv_pct(100));
lv_obj_set_height( ui_timerheader, lv_pct(20));
lv_obj_set_align( ui_timerheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_timerheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_timerheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_timerheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_timerheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_timerheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_timerheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_timerheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_timerheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_timerheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_timerheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_timerheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_timerheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_timerheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timertitle = lv_label_create(ui_timerheader);
lv_obj_set_width( ui_timertitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_timertitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_timertitle, 30 );
lv_obj_set_y( ui_timertitle, -2 );
lv_obj_set_align( ui_timertitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_timertitle,"定时器实验");

ui_timerpanel = lv_obj_create(ui_timeui);
lv_obj_set_width( ui_timerpanel, lv_pct(100));
lv_obj_set_height( ui_timerpanel, lv_pct(80));
lv_obj_set_x( ui_timerpanel, lv_pct(0) );
lv_obj_set_y( ui_timerpanel, lv_pct(20) );
lv_obj_set_align( ui_timerpanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_timerpanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_timerpanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_timerpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_timerpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_timerpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_timerpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_timerpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timerSpinbox = lv_spinbox_create(ui_timerpanel);
lv_obj_set_width( ui_timerSpinbox, 70);
lv_obj_set_height( ui_timerSpinbox, 42);
lv_obj_set_align( ui_timerSpinbox, LV_ALIGN_CENTER );
lv_spinbox_set_digit_format( ui_timerSpinbox, 4, 2);
lv_spinbox_set_range( ui_timerSpinbox, 0,9999 );
lv_spinbox_set_step( ui_timerSpinbox, round(pow(10, 1 - 1)) );

lv_obj_add_event_cb(ui_timerSpinbox, ui_event_timerSpinbox, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_timeui, ui_event_timeui, LV_EVENT_ALL, NULL);

}
