// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_uartui_screen_init(void)
{
ui_uartui = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uartui, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uartheader = lv_obj_create(ui_uartui);
lv_obj_set_width( ui_uartheader, lv_pct(100));
lv_obj_set_height( ui_uartheader, lv_pct(20));
lv_obj_set_align( ui_uartheader, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_uartheader,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_uartheader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_uartheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_uartheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uartheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_uartheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_uartheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_uartheader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_uartheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_uartheader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_uartheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uartheader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uartheader, &ui_font_misans16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uarttitle = lv_label_create(ui_uartheader);
lv_obj_set_width( ui_uarttitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uarttitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uarttitle, 30 );
lv_obj_set_y( ui_uarttitle, -2 );
lv_obj_set_align( ui_uarttitle, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_uarttitle,"UART实验");

ui_TXpanel = lv_obj_create(ui_uartui);
lv_obj_set_width( ui_TXpanel, lv_pct(100));
lv_obj_set_height( ui_TXpanel, lv_pct(20));
lv_obj_set_x( ui_TXpanel, lv_pct(0) );
lv_obj_set_y( ui_TXpanel, lv_pct(20) );
lv_obj_set_align( ui_TXpanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_TXpanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TXpanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_TXpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_txlabel = lv_label_create(ui_TXpanel);
lv_obj_set_width( ui_txlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_txlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_txlabel, -87 );
lv_obj_set_y( ui_txlabel, -33 );
lv_obj_set_align( ui_txlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_txlabel,"TX");

ui_txtext = lv_textarea_create(ui_TXpanel);
lv_obj_set_width( ui_txtext, lv_pct(93));
lv_obj_set_height( ui_txtext, lv_pct(210));
lv_obj_set_align( ui_txtext, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_txtext,"Placeholder...");



ui_RXpanel = lv_obj_create(ui_uartui);
lv_obj_set_width( ui_RXpanel, lv_pct(100));
lv_obj_set_height( ui_RXpanel, lv_pct(20));
lv_obj_set_x( ui_RXpanel, lv_pct(0) );
lv_obj_set_y( ui_RXpanel, lv_pct(40) );
lv_obj_set_align( ui_RXpanel, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_RXpanel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_RXpanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_RXpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rxlabel = lv_label_create(ui_RXpanel);
lv_obj_set_width( ui_rxlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rxlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_rxlabel, -87 );
lv_obj_set_y( ui_rxlabel, -33 );
lv_obj_set_align( ui_rxlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_rxlabel,"RX");

ui_rxtext = lv_textarea_create(ui_RXpanel);
lv_obj_set_width( ui_rxtext, lv_pct(93));
lv_obj_set_height( ui_rxtext, lv_pct(210));
lv_obj_set_align( ui_rxtext, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_rxtext,"Placeholder...");



ui_uartkeyboard = lv_keyboard_create(ui_uartui);
lv_obj_set_width( ui_uartkeyboard, lv_pct(100));
lv_obj_set_height( ui_uartkeyboard, lv_pct(41));
lv_obj_set_x( ui_uartkeyboard, lv_pct(0) );
lv_obj_set_y( ui_uartkeyboard, lv_pct(60) );
lv_obj_set_align( ui_uartkeyboard, LV_ALIGN_TOP_MID );

lv_obj_add_event_cb(ui_txtext, ui_event_txtext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rxtext, ui_event_rxtext, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uartkeyboard, ui_event_uartkeyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_uartui, ui_event_uartui, LV_EVENT_ALL, NULL);

}
