// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "../ui.h"

void ui_wifiset_screen_init(void)
{
    ui_wifiset = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_wifiset, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wifiset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiset, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifiset, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wlanheader = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_wlanheader, lv_pct(100));
    lv_obj_set_height(ui_wlanheader, lv_pct(20));
    lv_obj_set_align(ui_wlanheader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_wlanheader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wlanheader, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wlanheader, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wlanheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wlanheader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wlanheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wlanheader, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wlanheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wlanheader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wlanheader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wlanheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wlanheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wlanheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wlanheader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_wlanheader, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wlanheader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wlanheader, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_headerbackico = lv_label_create(ui_wlanheader);
    lv_obj_set_width(ui_headerbackico, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_headerbackico, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_headerbackico, 10);
    lv_obj_set_y(ui_headerbackico, -3);
    lv_obj_set_align(ui_headerbackico, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_headerbackico, "");
    lv_obj_add_flag(ui_headerbackico, LV_OBJ_FLAG_CLICKABLE); /// Flags
    lv_obj_set_style_text_font(ui_headerbackico, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wlantitle = lv_label_create(ui_wlanheader);
    lv_obj_set_width(ui_wlantitle, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wlantitle, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wlantitle, 30);
    lv_obj_set_y(ui_wlantitle, -2);
    lv_obj_set_align(ui_wlantitle, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_wlantitle, "WLAN设置");

    ui_wlansetpannel = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_wlansetpannel, lv_pct(100));
    lv_obj_set_height(ui_wlansetpannel, lv_pct(80));
    lv_obj_set_x(ui_wlansetpannel, lv_pct(0));
    lv_obj_set_y(ui_wlansetpannel, lv_pct(20));
    lv_obj_set_align(ui_wlansetpannel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_wlansetpannel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_wlansetpannel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wlansetpannel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wlansetpannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wlansetpannel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wlansetpannel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wlansetpannel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wlanswitchpanel = lv_obj_create(ui_wlansetpannel);
    lv_obj_set_width(ui_wlanswitchpanel, lv_pct(100));
    lv_obj_set_height(ui_wlanswitchpanel, lv_pct(20));
    lv_obj_set_align(ui_wlanswitchpanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_wlanswitchpanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_wlanswitchpanel, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_wlanswitchpanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wlanswitchpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wlanswitchpanel, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wlanswitchpanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wlanswitchpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wlanswitchpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wlanswitchpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wlanswitchpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wlanswitchpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wlansetlabel = lv_label_create(ui_wlanswitchpanel);
    lv_obj_set_width(ui_wlansetlabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wlansetlabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wlansetlabel, 0);
    lv_obj_set_y(ui_wlansetlabel, 4);
    lv_label_set_text(ui_wlansetlabel, "WLAN");

    ui_wlanswitch = lv_switch_create(ui_wlanswitchpanel);
    lv_obj_set_width(ui_wlanswitch, 45);
    lv_obj_set_height(ui_wlanswitch, 24);
    lv_obj_set_align(ui_wlanswitch, LV_ALIGN_TOP_RIGHT);

    lv_obj_set_style_bg_color(ui_wlanswitch, lv_color_hex(0xAAAAAA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wlanswitch, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wlanswitch, lv_color_hex(0x00D200), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_wlanswitch, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_wificonnect = lv_obj_create(ui_wlansetpannel);
    lv_obj_set_width(ui_wificonnect, lv_pct(100));
    lv_obj_set_height(ui_wificonnect, lv_pct(30));
    lv_obj_set_x(ui_wificonnect, 0);
    lv_obj_set_y(ui_wificonnect, 45);
    lv_obj_set_align(ui_wificonnect, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_wificonnect, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wificonnect, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_wificonnect, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_wificonnect, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wificonnect, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wificonnect, lv_color_hex(0x0078F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wificonnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wificonnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifisymbol = lv_label_create(ui_wificonnect);
    lv_obj_set_width(ui_wifisymbol, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifisymbol, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wifisymbol, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifisymbol, "");
    lv_obj_set_style_text_color(ui_wifisymbol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifisymbol, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifisymbol, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiname = lv_label_create(ui_wificonnect);
    lv_obj_set_width(ui_wifiname, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifiname, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifiname, 35);
    lv_obj_set_y(ui_wifiname, 0);
    lv_label_set_text(ui_wifiname, "cmcc-4g");
    lv_obj_set_style_text_color(ui_wifiname, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifiname, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistats = lv_label_create(ui_wificonnect);
    lv_obj_set_width(ui_wifistats, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifistats, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifistats, 35);
    lv_obj_set_y(ui_wifistats, 0);
    lv_obj_set_align(ui_wifistats, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_wifistats, "已连接");
    lv_obj_set_style_text_color(ui_wifistats, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifistats, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wificlock = lv_label_create(ui_wificonnect);
    lv_obj_set_width(ui_wificlock, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wificlock, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wificlock, -20);
    lv_obj_set_y(ui_wificlock, 0);
    lv_obj_set_align(ui_wificlock, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wificlock, "");
    lv_obj_set_style_text_color(ui_wificlock, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wificlock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wificlock, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wificonright = lv_label_create(ui_wificonnect);
    lv_obj_set_width(ui_wificonright, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wificonright, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wificonright, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wificonright, "");
    lv_obj_set_style_text_color(ui_wificonright, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wificonright, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wificonright, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiscan = lv_obj_create(ui_wlansetpannel);
    lv_obj_set_width(ui_wifiscan, lv_pct(100));
    lv_obj_set_height(ui_wifiscan, lv_pct(20));
    lv_obj_set_x(ui_wifiscan, 0);
    lv_obj_set_y(ui_wifiscan, 125);
    lv_obj_set_align(ui_wifiscan, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_wifiscan, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_wifiscan, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiscan, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_wifiscan, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wifiscan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiscan, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiscan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifiscan, lv_color_hex(0xB4B4B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifiscan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiscan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifiscan, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wifiscan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wifiscan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wifiscan, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wifiscan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiselecttitle = lv_label_create(ui_wifiscan);
    lv_obj_set_height(ui_wifiselecttitle, LV_SIZE_CONTENT); /// 1
    lv_obj_set_flex_grow(ui_wifiselecttitle, 1);
    lv_obj_set_align(ui_wifiselecttitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifiselecttitle, "选取附近的WLAN");
    lv_obj_set_style_text_font(ui_wifiselecttitle, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifiselecttitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifirefresh = lv_label_create(ui_wifiscan);
    lv_obj_set_width(ui_wifirefresh, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifirefresh, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wifirefresh, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifirefresh, "");
    lv_obj_set_style_text_font(ui_wifirefresh, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifilist = lv_obj_create(ui_wlansetpannel);
    lv_obj_set_width(ui_wifilist, lv_pct(100));
    lv_obj_set_height(ui_wifilist, lv_pct(20));
    lv_obj_set_align(ui_wifilist, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifilist, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_wifilist, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_wifilist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifilist, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifilist, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifilist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wifilist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wifilist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wifilist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wifilist, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifisymbol1 = lv_label_create(ui_wifilist);
    lv_obj_set_width(ui_wifisymbol1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifisymbol1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wifisymbol1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifisymbol1, "");
    lv_obj_set_style_text_font(ui_wifisymbol1, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifilistname = lv_label_create(ui_wifilist);
    lv_obj_set_width(ui_wifilistname, 200);
    lv_obj_set_height(ui_wifilistname, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifilistname, 30);
    lv_obj_set_y(ui_wifilistname, 0);
    lv_obj_set_align(ui_wifilistname, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_wifilistname, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_wifilistname, "MAXHUB-433");
    lv_obj_add_flag(ui_wifilistname, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE); /// Flags

    ui_wifilock = lv_label_create(ui_wifilist);
    lv_obj_set_width(ui_wifilock, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifilock, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifilock, -20);
    lv_obj_set_y(ui_wifilock, 0);
    lv_obj_set_align(ui_wifilock, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifilock, "");
    lv_obj_set_style_text_font(ui_wifilock, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifilistright = lv_label_create(ui_wifilist);
    lv_obj_set_width(ui_wifilistright, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifilistright, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wifilistright, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifilistright, "");
    lv_obj_set_style_text_font(ui_wifilistright, &ui_font_symbols16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enterwifipass = lv_obj_create(ui_wifiset);
    lv_obj_set_width(ui_enterwifipass, lv_pct(100));
    lv_obj_set_height(ui_enterwifipass, lv_pct(120));
    lv_obj_set_x(ui_enterwifipass, 0);
    lv_obj_set_y(ui_enterwifipass, 240);
    lv_obj_set_align(ui_enterwifipass, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_enterwifipass, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_enterwifipass, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_enterwifipass, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_enterwifipass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_enterwifipass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_enterwifipass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_enterwifipass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passpannel = lv_obj_create(ui_enterwifipass);
    lv_obj_set_width(ui_passpannel, lv_pct(100));
    lv_obj_set_height(ui_passpannel, lv_pct(40));
    lv_obj_set_x(ui_passpannel, -1);
    lv_obj_set_y(ui_passpannel, 3);
    lv_obj_set_align(ui_passpannel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_passpannel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_wifinamelabel = lv_label_create(ui_passpannel);
    lv_obj_set_width(ui_wifinamelabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifinamelabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifinamelabel, lv_pct(-3));
    lv_obj_set_y(ui_wifinamelabel, lv_pct(-16));
    lv_obj_set_align(ui_wifinamelabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_wifinamelabel, "MAXHUB-433");
    lv_obj_set_style_text_font(ui_wifinamelabel, &ui_font_misans16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifipassinput = lv_textarea_create(ui_passpannel);
    lv_obj_set_width(ui_wifipassinput, lv_pct(100));
    lv_obj_set_height(ui_wifipassinput, LV_SIZE_CONTENT); /// 25
    lv_obj_set_x(ui_wifipassinput, lv_pct(0));
    lv_obj_set_y(ui_wifipassinput, lv_pct(-11));
    lv_obj_set_align(ui_wifipassinput, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_wifipassinput, 64);
    lv_textarea_set_placeholder_text(ui_wifipassinput, "密码");
    lv_textarea_set_one_line(ui_wifipassinput, true);
    lv_textarea_set_password_mode(ui_wifipassinput, true);
    lv_obj_clear_flag(ui_wifipassinput, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_border_color(ui_wifipassinput, lv_color_hex(0x0079F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifipassinput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifipassinput, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connectbtn = lv_btn_create(ui_passpannel);
    lv_obj_set_width(ui_connectbtn, lv_pct(43));
    lv_obj_set_height(ui_connectbtn, lv_pct(50));
    lv_obj_set_x(ui_connectbtn, lv_pct(3));
    lv_obj_set_y(ui_connectbtn, lv_pct(17));
    lv_obj_set_align(ui_connectbtn, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_connectbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_connectbtn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_connectbtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_connectbtn, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connectbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_connectbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_connectbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_connectbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_connectbtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_connectbtn, lv_color_hex(0x1D87F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_connectbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_radius(ui_connectbtn, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_connectbtn, lv_color_hex(0x1D87F5), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_connectbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_connectbtn, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_connecttext = lv_label_create(ui_connectbtn);
    lv_obj_set_width(ui_connecttext, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_connecttext, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_connecttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_connecttext, "连接");

    ui_canceltbtn = lv_btn_create(ui_passpannel);
    lv_obj_set_width(ui_canceltbtn, lv_pct(43));
    lv_obj_set_height(ui_canceltbtn, lv_pct(50));
    lv_obj_set_x(ui_canceltbtn, lv_pct(-3));
    lv_obj_set_y(ui_canceltbtn, lv_pct(17));
    lv_obj_set_align(ui_canceltbtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_canceltbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_canceltbtn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_canceltbtn, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_canceltbtn, lv_color_hex(0xE6E6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_canceltbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_canceltbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_canceltbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_canceltbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_canceltbtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_canceltbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_canceltbtn, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_canceltbtn, lv_color_hex(0x1D87F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_canceltbtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_canceltbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_canceltbtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_radius(ui_canceltbtn, 0, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_canceltbtn, lv_color_hex(0x1D87F5), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_canceltbtn, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_canceltbtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_canceltbtn, 255, LV_PART_MAIN | LV_STATE_CHECKED | LV_STATE_PRESSED);

    ui_canceltext = lv_label_create(ui_canceltbtn);
    lv_obj_set_width(ui_canceltext, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_canceltext, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_canceltext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_canceltext, "取消");

    ui_keypannel = lv_obj_create(ui_enterwifipass);
    lv_obj_set_width(ui_keypannel, lv_pct(100));
    lv_obj_set_height(ui_keypannel, lv_pct(42));
    lv_obj_set_align(ui_keypannel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_keypannel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Keyboard = lv_keyboard_create(ui_keypannel);
    lv_obj_set_width(ui_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_Keyboard, lv_pct(100));
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_Keyboard, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_headerbackico, ui_event_headerbackico, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wlanswitch, ui_event_wlanswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifirefresh, ui_event_wifirefresh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifilistname, ui_event_wifilistname, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_wifipassinput, ui_event_wifipassinput, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_connectbtn, ui_event_connectbtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_canceltbtn, ui_event_canceltbtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_wifipassinput);
    lv_obj_add_event_cb(ui_wifiset, ui_event_wifiset, LV_EVENT_ALL, NULL);
}
