// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#include "ui.h"

void backlight(lv_event_t * e)
{
	// Your code here
}

void volumesetting(lv_event_t * e)
{
	// Your code here
}

void isrTestCb_0(lv_event_t * e)
{
	// Your code here
}

void isrTestCb_1(lv_event_t * e)
{
	// Your code here
}

void isrTestCb_2(lv_event_t * e)
{
	// Your code here
}

void timeTestCb(lv_event_t * e)
{

}

void adTestCb(lv_event_t * e)
{
	// Your code here
}

void pwmTestCb(lv_event_t * e)
{
	// Your code here
}

void daTestCb(lv_event_t * e)
{
	// Your code here
}

void uartTestCb(lv_event_t * e)
{
	// Your code here
}

void i2cTestCb(lv_event_t * e)
{
	// Your code here
}

void wifiscanf(lv_event_t * e)
{
	// Your code here
}

void wifistart(lv_event_t * e)
{
	// Your code here
}

void wificlose(lv_event_t * e)
{
	// Your code here
}

void wifisanf(lv_event_t * e)
{
	// Your code here
}

void connectwifi(lv_event_t * e)
{
	// Your code here
}

void gpioTest(lv_event_t * e)
{
	// Your code here
}

void spiTestCb(lv_event_t * e)
{
	// Your code here
}

void mqttTestCb(lv_event_t * e)
{
	// Your code here
}
