// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: timergui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void backlight(lv_event_t * e);
void volumesetting(lv_event_t * e);
void gpioTest(lv_event_t * e);
void isrTestCb_0(lv_event_t * e);
void isrTestCb_1(lv_event_t * e);
void isrTestCb_2(lv_event_t * e);
void timeTestCb(lv_event_t * e);
void adTestCb(lv_event_t * e);
void pwmTestCb(lv_event_t * e);
void daTestCb(lv_event_t * e);
void uartTestCb(lv_event_t * e);
void i2cTestCb(lv_event_t * e);
void spiTestCb(lv_event_t * e);
void mqttTestCb(lv_event_t * e);
void wifiscanf(lv_event_t * e);
void wifistart(lv_event_t * e);
void wificlose(lv_event_t * e);
void wifisanf(lv_event_t * e);
void connectwifi(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
